import React from "react";

const LaplaceExpression = () => {
  return (
    <div>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mo>|A|</mo>
        <mo>=</mo>
        <mrow>
          <mo>|</mo>
          <mtable>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>11</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>12</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>13</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>21</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>22</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>23</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>31</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>32</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>33</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
          </mtable>
          <mo>|</mo>
        </mrow>
      </math>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mo>=</mo>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>11</mi>
          </mrow>
        </msub>
        <mrow>
          <mo>|</mo>
          <mtable>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>22</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>23</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>32</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>33</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
          </mtable>
          <mo>|</mo>
        </mrow>
      </math>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mo>-</mo>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>12</mi>
          </mrow>
        </msub>
        <mrow>
          <mo>|</mo>
          <mtable>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>21</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>23</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>31</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>33</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
          </mtable>
          <mo>|</mo>
        </mrow>
      </math>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mo>+</mo>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>13</mi>
          </mrow>
        </msub>
        <mrow>
          <mo>|</mo>
          <mtable>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>21</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>22</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>31</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>32</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
          </mtable>
          <mo>|</mo>
        </mrow>
      </math>
      <p className="after-formula">
        donde esta el{" "}
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <msub>
            <mi>a</mi>
            <mrow>
              <mi>ij</mi>
            </mrow>
          </msub>
        </math>{" "}
        que corresponde a un elemento de la matriz y del{" "}
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <msub>
            <mi>c</mi>
            <mrow>
              <mi>ij</mi>
            </mrow>
          </msub>
        </math>{" "}
        es el cofactor del{" "}
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <msub>
            <mi>a</mi>
            <mrow>
              <mi>ij</mi>
            </mrow>
          </msub>
        </math>{" "}
        del elemento
      </p>
    </div>
  );
};

export default LaplaceExpression;
