import React from "react";

const matrix3x3 = () => {
  return (
    <div>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <msub>
          <mi>A</mi>
          <mrow>
            <mi>3x3</mi>
          </mrow>
        </msub>
        <mo>=</mo>
        <mrow>
          <mo>[</mo>
          <mtable>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>11</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>12</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>13</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>21</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>22</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>23</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>31</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>32</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>33</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
          </mtable>
          <mo>]</mo>
        </mrow>
      </math>
    </div>
  );
};

export default matrix3x3;
