import React from 'react'

const SarrusExpression = () => {
  return (
    <div>
              <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mrow>
          <mo>|</mo>
          <mtable>
            <mtr>
              <mtd>
                <mi>a</mi>
              </mtd>
              <mtd>
                <mi>b</mi>
              </mtd>
              <mtd>
                <mi>c</mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>d</mi>
              </mtd>
              <mtd>
                <mi>e</mi>
              </mtd>
              <mtd>
                <mi>f</mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>g</mi>
              </mtd>
              <mtd>
                <mi>h</mi>
              </mtd>
              <mtd>
                <mi>i</mi>
              </mtd>
            </mtr>
          </mtable>
          <mo>|</mo>
          <mo>=</mo>
        </mrow>
      </math>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mrow>
          <mo>|</mo>
          <mtable>
            <mtr>
              <mtd>
                <mi>a</mi>
              </mtd>
              <mtd>
                <mi>b</mi>
              </mtd>
              <mtd>
                <mi>c</mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>d</mi>
              </mtd>
              <mtd>
                <mi>e</mi>
              </mtd>
              <mtd>
                <mi>f</mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>g</mi>
              </mtd>
              <mtd>
                <mi>h</mi>
              </mtd>
              <mtd>
                <mi>i</mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>a</mi>
              </mtd>
              <mtd>
                <mi>b</mi>
              </mtd>
              <mtd>
                <mi>c</mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>d</mi>
              </mtd>
              <mtd>
                <mi>e</mi>
              </mtd>
              <mtd>
                <mi>f</mi>
              </mtd>
            </mtr>
          </mtable>
          <mo>|</mo>
          <mo>=</mo>
        </mrow>
      </math>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mrow>
          <mo>(</mo>
          <mrow>
            <mrow>
              <mi>a</mi>
              <mo>*</mo>
              <mi>e</mi>
              <mo>*</mo>
              <mi>i</mi>
            </mrow>
            <mo>+</mo>
            <mrow>
              <mi>b</mi>
              <mo>*</mo>
              <mi>f</mi>
              <mo>*</mo>
              <mi>g</mi>
            </mrow>
            <mo>+</mo>
            <mrow>
              <mi>c</mi>
              <mo>*</mo>
              <mi>d</mi>
              <mo>*</mo>
              <mi>h</mi>
            </mrow>
          </mrow>
          <mo>)</mo>
        </mrow>
      </math>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mo>-</mo>
      </math>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mo>(</mo>
        <mrow>
          <mi>c</mi>
          <mo>*</mo>
          <mi>e</mi>
          <mo>*</mo>
          <mi>g</mi>
        </mrow>
        <mo>+</mo>
        <mrow>
          <mi>a</mi>
          <mo>*</mo>
          <mi>f</mi>
          <mo>*</mo>
          <mi>h</mi>
        </mrow>
        <mo>+</mo>
        <mrow>
          <mi>b</mi>
          <mo>*</mo>
          <mi>d</mi>
          <mo>*</mo>
          <mi>i</mi>
        </mrow>
        <mo>)</mo>
      </math>
    </div>
  )
}

export default SarrusExpression