import React from "react";

const SubmatrixM14_1 = () => {
  return (
    <div>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mrow>
          <mo>|</mo>
          <mtable>
            <mtr>
              <mtd>
                <mn>5</mn>
              </mtd>
              <mtd>
                <mn>6</mn>
              </mtd>
              <mtd>
                <mn>7</mn>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mn>9</mn>
              </mtd>
              <mtd>
                <mn>10</mn>
              </mtd>
              <mtd>
                <mn>11</mn>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mn>13</mn>
              </mtd>
              <mtd>
                <mn>14</mn>
              </mtd>
              <mtd>
                <mn>15</mn>
              </mtd>
            </mtr>
          </mtable>
          <mo>|</mo>
        </mrow>
        <mo>=</mo>
      </math>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mrow>
          <mo>(</mo>
          <mn>5</mn>
          <mo>&#215;</mo>
          <mrow>
            <mo>|</mo>
            <mtable>
              <mtr>
                <mtd>
                  <mn>10</mn>
                </mtd>
                <mtd>
                  <mn>11</mn>
                </mtd>
              </mtr>
              <mtr>
                <mtd>
                  <mn>14</mn>
                </mtd>
                <mtd>
                  <mn>15</mn>
                </mtd>
              </mtr>
            </mtable>
            <mo>|</mo>
          </mrow>
          <mo>)</mo>
        </mrow>
      </math>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mrow>
          <mo>-</mo>
          <mo>(</mo>
          <mn>6</mn>
          <mo>&#215;</mo>
          <mrow>
            <mo>|</mo>
            <mtable>
              <mtr>
                <mtd>
                  <mn>9</mn>
                </mtd>
                <mtd>
                  <mn>11</mn>
                </mtd>
              </mtr>
              <mtr>
                <mtd>
                  <mn>13</mn>
                </mtd>
                <mtd>
                  <mn>15</mn>
                </mtd>
              </mtr>
            </mtable>
            <mo>|</mo>
          </mrow>
          <mo>)</mo>
        </mrow>
      </math>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mrow>
          <mo>+</mo>
          <mo>(</mo>
          <mn>7</mn>
          <mo>&#215;</mo>
          <mrow>
            <mo>|</mo>
            <mtable>
              <mtr>
                <mtd>
                  <mn>9</mn>
                </mtd>
                <mtd>
                  <mn>10</mn>
                </mtd>
              </mtr>
              <mtr>
                <mtd>
                  <mn>13</mn>
                </mtd>
                <mtd>
                  <mn>14</mn>
                </mtd>
              </mtr>
            </mtable>
            <mo>|</mo>
          </mrow>
          <mo>)</mo>
        </mrow>
      </math>
    </div>
  );
};

export default SubmatrixM14_1;
