import React from "react";
import "./det.css";

const Sarrus = () => {
  return (
    <div>
      <h2>Regla de Sarrus</h2>
      <p>
        La regla de Sarrus es un método que permite calcular rápidamente el
        determinante de una matriz cuadrada con tamaño de 3×3 únicamente. En
        otras palabras, la regla de Sarrus consiste en dibujar dos conjuntos de
        dos triángulos opuestos mediante los elementos de la matriz. El primer
        conjunto serán 2 triángulos que cruzarán la diagonal principal y el
        segundo conjunto serán 2 triángulos que cruzarán la diagonal secundaria.
      </p>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mrow>
          <mo>|</mo>
          <mtable>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>11</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>12</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>13</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>21</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>22</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>23</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>31</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>32</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>33</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
          </mtable>
          <mo>|</mo>
        </mrow>{" "}
        <mo>=</mo>
        <mrow>
          <mo>|</mo>
          <mtable>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>11</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>12</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>13</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>21</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>22</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>23</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>31</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>32</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>33</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>11</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>12</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>13</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>21</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>22</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
              <mtd>
                <mi>
                  <msub>
                    <mi>a</mi>
                    <mrow>
                      <mi>23</mi>
                    </mrow>
                  </msub>
                </mi>
              </mtd>
            </mtr>
          </mtable>
          <mo>|</mo>
        </mrow>{" "}
        <mo>=</mo>
        <mo>[</mo>
        <mo>(</mo>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>11</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>22</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>33</mi>
          </mrow>
        </msub>
        <mo>)</mo>
        <mo>+</mo>
        <mo>(</mo>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>21</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>32</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>13</mi>
          </mrow>
        </msub>
        <mo>)</mo>
        <mo>+</mo>
        <mo>(</mo>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>31</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>12</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>23</mi>
          </mrow>
        </msub>
        <mo>)</mo>
        <mo>]</mo>
        <mo>-</mo>
        <mo>[</mo>
        <mo>(</mo>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>13</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>22</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>31</mi>
          </mrow>
        </msub>
        <mo>)</mo>
        <mo>+</mo>
        <mo>(</mo>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>23</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>32</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>11</mi>
          </mrow>
        </msub>
        <mo>)</mo>
        <mo>+</mo>
        <mo>(</mo>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>33</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>12</mi>
          </mrow>
        </msub>
        <msub>
          <mi>a</mi>
          <mrow>
            <mi>21</mi>
          </mrow>
        </msub>
        <mo>)</mo>
        <mo>]</mo>
      </math>

    </div>
  );
};

export default Sarrus;
